# Global Docker image parameters
# Please, note that this will override the image parameters, including dependencies, configured to use the global value
# Current available global Docker image parameters: imageRegistry
#
# global:
#   imageRegistry: myRegistryName

# String to partially override fullname template (will maintain the release name)
#
# nameOverride:

# String to fully override fullname template
#
# fullnameOverride:

# ref: https://hub.docker.com/r/gogs/gogs/tags
#
image:
  registry: docker.io
  repository: tranchung/gogs
  tag: latest
  # Specify a imagePullPolicy
  # Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  # ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  #
  pullPolicy: IfNotPresent

replicas: 1

# Gogs settings
# ref: https://gogs.io/docs/advanced/configuration_cheat_sheet
#      https://github.com/gogs/gogs/blob/master/conf/app.ini

# You can provide your own custom app.ini setting instead
# If existingConfigMap is provided, make sure it has a key name `app.ini`
# and contain all required params that gogs requires.
# Also, when provided, `gogs` key will be ignored.
existingConfigMap: ""

gogs:
  # App name that shows on every page title
  appName: Gogs

  # Either "dev", "prod" or "test"
  runMode: prod

  # Domain where gogs is running
  # Should match the domain of ingress.host
  domain: example.com

  # Complete URL with protocol where gogs can be reached
  # Should match URL of ingress.host
  rootUrl: https://gogs.example.com

  # Disable gogs SSH feature
  disableSsh: true

  # Start gogs SSH server
  # disableSsh should be false if this is set to true
  startSshServer: false

  # Upload max file fize in MB
  uploadMaxSize: 3

  # Maximum number of files per upload
  uploadMaxFiles: 5

  # Release max file size in MB
  releaseMaxSize: 32

  # Maximum number of files per release
  releaseMaxFiles: 10

  # Change to keep your data safe
  secretKey: ekohM3ukooN3BeiXouveegh8lahPeel4

  # User need to confirm e-mail for registration
  registerEmailConfirm: false

  # Does not allow register and admin create account only
  disableRegistration: false

  # User must sign in to view anything.
  requireSigninView: true

  # Mail notification
  enableNotifyEmail: false

  # More detail: https://github.com/gogits/gogs/issues/165
  enableReverseProxyAuthentication: false

  # Enable captcha validation for registration
  enableCaptcha: true


database:
  # Either "mysql", "postgres" or "sqlite3"
  type: sqlite3
  host: 127.0.0.1
  port: 3306
  dbName: gogs
  dbUsername: gogs
  dbPassword: gogs

  # For "postgres" only, either "disable", "require" or "verify-full"
  sslMode: disable

  # For "sqlite3" only
  path: data/gogs.db

# Kubernetes configuration
# For minikube, set this to NodePort, elsewhere use LoadBalancer
#
service:
  # ClusterIP, LoadBalancer, or NodePort
  type: ClusterIP
  # HTTP Port
  port: 3000
  # loadBalancerIP:
  #
  # nodePort: <to set explicitly, choose port between 30000-32767>
  nodePort: ""
  #
  # Enable client source IP preservation
  # ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  #
  externalTrafficPolicy: Cluster
  # Service annotations done as key:value pairs
  annotations: {}

# Enable persistence using Persistent Volume Claims
# ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
#
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 2Gi
  # storageClass: ""

# Configure the ingress resource that allows you to access the
# ref: http://kubernetes.io/docs/user-guide/ingress/
#
ingress:
  # Set to true to enable ingress record generation
  enabled: false

  # Ingress annotations done as key:value pairs
  # For a full list of possible ingress annotations, please see
  # ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
  #
  # If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
  # If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
  annotations: {}
  #  kubernetes.io/ingress.class: nginx

  # The list of hostnames to be covered with this ingress record.
  # Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hosts:
  - name: gogs.local
    path: /

    # Set this to true in order to enable TLS on the ingress record
    tls: true

    # Optionally specify the TLS hosts for the ingress record
    # Useful when the Ingress controller supports www-redirection
    # If not specified, the above host name will be used
    # tlsHosts:
    # - www.gogs.local
    # - gogs.local

    # If TLS is set to true, you must declare what secret will store the key/certificate for TLS
    tlsSecret: gogs-tls-cert

# Extra environtment variables to append to deployment
extraEnvVars: {}

# Pod Upgrade Strategy
# ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
#
strategy: {}

# Pod Security Context
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
#
securityContext: {}

# Configure resource requests and limits
# ref: http://kubernetes.io/docs/user-guide/compute-resources/
#
resources: {}

# Node selector for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
#
nodeSelector: {}

# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
#
affinity: {}

